version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baby_journal
# In non production this is useful for testing
    ports:
      - "3307:3306"
    volumes:
      - ./db_data/:/docker-entrypoint-initdb.d
  redis:
    image: redis
  celery-worker:
    image: baby_journal:prod
    environment:
      CELERY_BROKER_URL: redis://redis
    entrypoint:
      - celery 
      - worker 
      - -A 
      - app.celery 
      - --loglevel=info
  baby_journal:
    image: baby_journal:prod
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - celery-worker
